version: "3.8"

services:
  db:
    image: postgres:14
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: "${POSTGRES_USER:-postgres}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD:-postgres}"
      POSTGRES_DB: "${POSTGRES_DB:-fastapi_db}"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${POSTGRES_USER:-postgres}"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    restart: always
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "${PORT:-8000}:8000"
    env_file:
      - .env
    volumes:
      - .:/app
    entrypoint: ["sh", "/app/entrypoint.sh"]
    # command é opcional; o entrypoint.sh já roda create_db.py e uvicorn

volumes:
  postgres_data:
